# last-translation-benchmark configuration file

DEEPL_API_KEY = ""
LIBRE_URL = ""
OPENROUTER_API_KEY = ""
LARA_API_ID = ""
LARA_API_SECRET = ""
GOOGLE_TRANSLATE_API_KEY = ""
ROR_CLIENT_ID = ""
NOMINATIM_SEARCH_URL = "https://nominatim.openstreetmap.org/search"
NOMINATIM_USER_AGENT = "last-translation-benchmark/0.0.1 (last-translation-benchmark@vilda.net)"

CONTRIBUTOR_QUOTA_DEFAULT = 100
DB_PATH = "data/db.sqlite"
DB_PATH_CACHE = "data/db_cache.sqlite"

# specific to our FORPSI email
EMAIL_SENDER = ""
EMAIL_PASSWORD = ""
EMAIL_SMTP_SERVER_PORT = ""
